version: "3.9"  # optional since v1.27.0
services:
  web_api:
    image: fsa.so.blazorwebapp
    build:
      context: .
      dockerfile: BlazorWebApp/Dockerfile # the Dockerfile is stored in the FSA.Map.WebApi project
      args:
        FEED_ACCESSTOKEN: ${FEED_ACCESSTOKEN}
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=https://+:443;http://+:80
    - ASPNETCORE_Kestrel__Certificates__Default__Password=zaqWE*123
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/MapsApiSSLCert.pfx
    ports:
      - "443:443"
      #- "5000:80"
    volumes:
      - ./Dockerizing_api/https:/https:ro
    container_name: SO-blazorwebapp
