//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorClassLibrary1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RazorClassLibrary1.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Document Type.
        /// </summary>
        internal static string AddDocumentType {
            get {
                return ResourceManager.GetString("AddDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service Order.
        /// </summary>
        internal static string AddServiceOrder {
            get {
                return ResourceManager.GetString("AddServiceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service Order Document.
        /// </summary>
        internal static string AddServiceOrderDocument {
            get {
                return ResourceManager.GetString("AddServiceOrderDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service Order Feature.
        /// </summary>
        internal static string AddServiceOrderFeature {
            get {
                return ResourceManager.GetString("AddServiceOrderFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service Order Register.
        /// </summary>
        internal static string AddServiceOrderRegister {
            get {
                return ResourceManager.GetString("AddServiceOrderRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service Order Task.
        /// </summary>
        internal static string AddServiceOrderTask {
            get {
                return ResourceManager.GetString("AddServiceOrderTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service Order Task Document.
        /// </summary>
        internal static string AddServiceOrderTaskDocument {
            get {
                return ResourceManager.GetString("AddServiceOrderTaskDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service Order Type.
        /// </summary>
        internal static string AddServiceOrderType {
            get {
                return ResourceManager.GetString("AddServiceOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supply.
        /// </summary>
        internal static string AddSupply {
            get {
                return ResourceManager.GetString("AddSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supply Operation.
        /// </summary>
        internal static string AddSupplyOperation {
            get {
                return ResourceManager.GetString("AddSupplyOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task State.
        /// </summary>
        internal static string AddTaskState {
            get {
                return ResourceManager.GetString("AddTaskState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document types.
        /// </summary>
        internal static string Documenttypes {
            get {
                return ResourceManager.GetString("Documenttypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Document Type.
        /// </summary>
        internal static string EditDocumentType {
            get {
                return ResourceManager.GetString("EditDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service Order.
        /// </summary>
        internal static string EditServiceOrder {
            get {
                return ResourceManager.GetString("EditServiceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service Order Document.
        /// </summary>
        internal static string EditServiceOrderDocument {
            get {
                return ResourceManager.GetString("EditServiceOrderDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service Order Feature.
        /// </summary>
        internal static string EditServiceOrderFeature {
            get {
                return ResourceManager.GetString("EditServiceOrderFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service Order Register.
        /// </summary>
        internal static string EditServiceOrderRegister {
            get {
                return ResourceManager.GetString("EditServiceOrderRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service Order Task.
        /// </summary>
        internal static string EditServiceOrderTask {
            get {
                return ResourceManager.GetString("EditServiceOrderTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service Order Task Document.
        /// </summary>
        internal static string EditServiceOrderTaskDocument {
            get {
                return ResourceManager.GetString("EditServiceOrderTaskDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service Order Type.
        /// </summary>
        internal static string EditServiceOrderType {
            get {
                return ResourceManager.GetString("EditServiceOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Supply Operation.
        /// </summary>
        internal static string EditSupplyOperation {
            get {
                return ResourceManager.GetString("EditSupplyOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task State.
        /// </summary>
        internal static string EditTaskState {
            get {
                return ResourceManager.GetString("EditTaskState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Ending Date.
        /// </summary>
        internal static string EstimatedEndingDate {
            get {
                return ResourceManager.GetString("EstimatedEndingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Date.
        /// </summary>
        internal static string ExecutionDate {
            get {
                return ResourceManager.GetString("ExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executor.
        /// </summary>
        internal static string Executor {
            get {
                return ResourceManager.GetString("Executor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masters.
        /// </summary>
        internal static string Masters {
            get {
                return ResourceManager.GetString("Masters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        internal static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Service Orden.
        /// </summary>
        internal static string ParentServiceOrder {
            get {
                return ResourceManager.GetString("ParentServiceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Order.
        /// </summary>
        internal static string ServiceOrder {
            get {
                return ResourceManager.GetString("ServiceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Orders.
        /// </summary>
        internal static string ServiceOrders {
            get {
                return ResourceManager.GetString("ServiceOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Orders Basic Layout.
        /// </summary>
        internal static string ServiceOrdersBasicLayout {
            get {
                return ResourceManager.GetString("ServiceOrdersBasicLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Orders Documents.
        /// </summary>
        internal static string ServiceOrdersDocuments {
            get {
                return ResourceManager.GetString("ServiceOrdersDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Orders Features.
        /// </summary>
        internal static string ServiceOrdersFeatures {
            get {
                return ResourceManager.GetString("ServiceOrdersFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Orders Registers.
        /// </summary>
        internal static string ServiceOrdersRegisters {
            get {
                return ResourceManager.GetString("ServiceOrdersRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Orders Tasks.
        /// </summary>
        internal static string ServiceOrdersTasks {
            get {
                return ResourceManager.GetString("ServiceOrdersTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Orders Tasks Documents.
        /// </summary>
        internal static string ServiceOrdersTasksDocuments {
            get {
                return ResourceManager.GetString("ServiceOrdersTasksDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Order Task.
        /// </summary>
        internal static string ServiceOrderTask {
            get {
                return ResourceManager.GetString("ServiceOrderTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Order Tasks.
        /// </summary>
        internal static string ServiceOrderTasks {
            get {
                return ResourceManager.GetString("ServiceOrderTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Order Tasks States.
        /// </summary>
        internal static string ServiceOrderTasksStates {
            get {
                return ResourceManager.GetString("ServiceOrderTasksStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Order Type.
        /// </summary>
        internal static string ServiceOrderType {
            get {
                return ResourceManager.GetString("ServiceOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Order Types.
        /// </summary>
        internal static string ServiceOrderTypes {
            get {
                return ResourceManager.GetString("ServiceOrderTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State From.
        /// </summary>
        internal static string StateFrom {
            get {
                return ResourceManager.GetString("StateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To State.
        /// </summary>
        internal static string StateTo {
            get {
                return ResourceManager.GetString("StateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplies.
        /// </summary>
        internal static string Supplies {
            get {
                return ResourceManager.GetString("Supplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Operation.
        /// </summary>
        internal static string SupplyOperation {
            get {
                return ResourceManager.GetString("SupplyOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Operations.
        /// </summary>
        internal static string SupplyOperations {
            get {
                return ResourceManager.GetString("SupplyOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        internal static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
